"""deploy general

Revision ID: 4b00087145e4
Revises: 
Create Date: 2018-03-04 13:26:56.560463

"""
from alembic import op
import sqlalchemy as sa
from db_models.models import Base
from db_models.config import Config as conf

# revision identifiers, used by Alembic.
revision = '4b00087145e4'
down_revision = None
branch_labels = None
depends_on = None

SCHEMA_NAME = Base.metadata.tables[conf.SCHEMA_TYPE+'.company'].schema

def upgrade():
    op.execute('CREATE SCHEMA %s' % SCHEMA_NAME)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='general'
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['general.company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='general'
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['general.employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='general'
    )
    # ### end Alembic commands ###


def downgrade():
    op.execute('DROP SCHEMA %s' % SCHEMA_NAME)    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager', schema='general')
    op.drop_table('employee', schema='general')
    op.drop_table('company', schema='general')
    # ### end Alembic commands ###
