"""deploy engineering

Revision ID: 56816e6cd4db
Revises: 4b00087145e4
Create Date: 2018-03-04 14:07:08.505201

"""
from alembic import op
import sqlalchemy as sa
from db_models.models import Base
from db_models.config import Config as conf

# revision identifiers, used by Alembic.
revision = '56816e6cd4db'
down_revision = None
branch_labels = None
depends_on = None

SCHEMA_NAME = Base.metadata.tables[conf.SCHEMA_TYPE+'.company'].schema

def upgrade():
    op.execute('CREATE SCHEMA %s' % SCHEMA_NAME)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='engineering'
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='engineering'
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['engineering.company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='engineering'
    )
    op.create_table('employee_product_bridge',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['engineering.employee.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['engineering.product.id'], ),
    schema='engineering'
    )
    op.create_table('engineer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['engineering.employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='engineering'
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['engineering.employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='engineering'
    )
    # ### end Alembic commands ###


def downgrade():
    op.execute('DROP SCHEMA %s' % SCHEMA_NAME)    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager', schema='engineering')
    op.drop_table('engineer', schema='engineering')
    op.drop_table('employee_product_bridge', schema='engineering')
    op.drop_table('employee', schema='engineering')
    op.drop_table('product', schema='engineering')
    op.drop_table('company', schema='engineering')
    # ### end Alembic commands ###
