"""deploy consulting

Revision ID: ab71430390b2
Revises: 4b00087145e4
Create Date: 2018-03-04 14:01:21.850085

"""
from alembic import op
import sqlalchemy as sa
from db_models.models import Base
from db_models.config import Config as conf

# revision identifiers, used by Alembic.
revision = 'ab71430390b2'
down_revision = None
branch_labels = None
depends_on = None

SCHEMA_NAME = Base.metadata.tables[conf.SCHEMA_TYPE+'.company'].schema

def upgrade():
    op.execute('CREATE SCHEMA %s' % SCHEMA_NAME)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='consulting'
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='consulting'
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['consulting.company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='consulting'
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('client', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client'], ['consulting.client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='consulting'
    )
    op.create_table('consultant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['consulting.employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='consulting'
    )
    op.create_table('employee_project_bridge',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['consulting.employee.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['consulting.project.id'], ),
    schema='consulting'
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['consulting.employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='consulting'
    )
    # ### end Alembic commands ###


def downgrade():
    op.execute('DROP SCHEMA %s' % SCHEMA_NAME)    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager', schema='consulting')
    op.drop_table('employee_project_bridge', schema='consulting')
    op.drop_table('consultant', schema='consulting')
    op.drop_table('project', schema='consulting')
    op.drop_table('employee', schema='consulting')
    op.drop_table('company', schema='consulting')
    op.drop_table('client', schema='consulting')
    # ### end Alembic commands ###
